Repository mattermost/mattermost-plugin-aws-SNS, pull requests merged in 2019-06, with the labels that each got.

#15 Update System Console page, in preparation for GA release
  plugin.json
Labels: 3: Reviews Complete

#16 Update README, in preparation for GA release
  README.md
Labels: 2: Dev Review

#17 bug and version bump
  plugin.json
  server/manifest.go
  server/plugin.go
Labels: 2: Dev Review

#19 Replacing new lines with spaces in System Console settings page
  plugin.json
Labels: 3: Reviews Complete

#20 version bump
  plugin.json
  server/manifest.go
Labels: 1: PM Review

#21 Remove Markdown link, add period to plugin description
  plugin.json
Labels: 2: Dev Review
